### ISSUE TITLE
question about the hyperenclave sdk source code

### ISSUE THREAD

**Issue by Ariel08081214** [HyperEnclave/hyperenclave#20]
hai，I am really interested in HyperEncalve，so I followed the readme steps to deploy the hyperenclave. 
But I didn't see anything about the source code flow in the documentation. Have any suggestion about further research for hyperenclave？

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 , thanks for you interest on HyperEnclave.

> so I followed the readme steps to deploy the hyperenclave.

Can you successfully deploy HyperEnclave? We are willing to help you if your meet some problems. Don't hesitate to share your issues with us.

> But I didn't see anything about the source code flow in the documentation.

Currently there is no documentation on HyperEnclave's source code. As more and more people take interest on HyperEnclave, we are now considering documenting HyperEnclave on its technical details, contribution guide, etc.

For the question on how to research on HyperEnclave, the answer depends on your research requirements.
**Could you please share your insights or ideas with us? We may better help you according on your needs.**

If you want to take a deep dive into HyperEnclave's implementation, here may be some guides.
The functionality of HyperEnclave can be mainly divided into the following three parts:
1. How to set up the platform's environment when starting HyperEnclave.
2. How to provide TEE's capability through ISAs(Instruction Set Architecture);
3. How to react with hardware event.

Most developers or researchers are interested on the functionality 2. HyperEnclave's opensource part only provides ISAs process-based TEE's construction, which is similar to SGX. All the HyperCall types are listed in `pub num HyperCallCode` in `src/hypercall/mod.rs`. You may see the details of HyperCalls that you are interested in.

Notice that the title of this issue is "**question about the hyperenclave sdk source code**", I guess that you may want to get some details of HyperEnclave SDK. But its source code is not open-sourced now. HyperEnclave's SDK is based on SGX SDK, and their implementations are quite similar, since HyperEnclave provides the ISA which is similar to SGX. Maybe you could get some inspiration from it.

**Comment by Ariel08081214** [comment]
I'm soooo  thankful for your detailed reply. 
I deployed hyperenclave on Intel CPU and run some demo application successfuly. And I have read the related paper for deep research. Now one thing confuse me.Does normal applications can run on hyperenclave without modification when the hardware is HYGON CPU or other non-intel CPU？Does the occlum been extended for HYGON CPU？

**Comment by Ariel08081214** [comment]
I'm soooo  thankful for your detailed reply. 
I deployed hyperenclave on Intel CPU and run some demo application successfuly. After that  I read the related paper for deep research. Now one thing confuse me.Does normal applications can run on hyperenclave without modification when the hardware is HYGON CPU or other non-intel CPU？Does the occlum been extended for non-intel CPU？

**Comment by Ariel08081214** [comment]
I'm soooo thankful for your detailed reply.
I deployed hyperenclave on Intel CPU and run some demo application successfuly. After that I read the related paper for deep research. Now one thing confuse me.Does normal applications can run on hyperenclave without modification when the hardware is HYGON CPU or other non-intel CPU？Does the occlum been extended for non-intel CPU？@Bonjourz

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 

> Does normal applications can run on hyperenclave without modification when the hardware is HYGON CPU or other non-intel CPU？

Application developed by SGX SDK should be recompiled by HyperEnclave SDK, then it is able to run atop HyperEnclave on HYGON CPU or AMD CPU.

> Does the occlum been extended for non-intel CPU？

HyperEnclave-based Occlum has been extended.

**Comment by Ariel08081214** [comment]
> Hi @Ariel08081214
> 
> > Does normal applications can run on hyperenclave without modification when the hardware is HYGON CPU or other non-intel CPU？
> 
> Application developed by SGX SDK should be recompiled by HyperEnclave SDK, then it is able to run atop HyperEnclave on HYGON CPU or AMD CPU.
> 
> > Does the occlum been extended for non-intel CPU？
> 
> HyperEnclave-based Occlum has been extended.

Does it means that old applications can run on HYGON CPU by HyperEnclave-based Occlum without code refactoring？Is there any guide for deploying HyperEnclave on HYGON server？

**Comment by Ariel08081214** [comment]
> Hi @Ariel08081214
> 
> > Does normal applications can run on hyperenclave without modification when the hardware is HYGON CPU or other non-intel CPU？
> 
> Application developed by SGX SDK should be recompiled by HyperEnclave SDK, then it is able to run atop HyperEnclave on HYGON CPU or AMD CPU.
> 
> > Does the occlum been extended for non-intel CPU？
> 
> HyperEnclave-based Occlum has been extended.

Does it means that old applications can run on HYGON CPU by HyperEnclave-based Occlum without code refactoring？Is there any guide for deploying HyperEnclave on HYGON CPU ？

**Comment by Bonjourz** [comment]
@Ariel08081214 

> Does it means that old applications can run on HYGON CPU by HyperEnclave-based Occlum without code refactoring?

If the old application is runnable on [Occlum](https://github.com/occlum/occlum), then it is runnable on HyperEnclave-based Occlum.

> Is there any guide for deploying HyperEnclave on HYGON CPU ？

See HyperEnclave's [README](https://github.com/HyperEnclave/hyperenclave/blob/master/README.md)

By the way, it seems that your issue: **"question about the hyperenclave sdk source code"** has been addressed. Could you please close this issue?

If you want to discuss some other topics, you need to open another issue discussion.
